name: growl

services:
  api:
    container_name: api
    build:
      context: ..
      dockerfile: docker/dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@database:5432/growl?schema=public"
    restart: always

  database:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    restart: always

  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - "88:88"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

volumes:
  db-data:
